const fs = require("node:fs");

function generateUUIDv1() {
    const timestamp = Date.now();
    const timeHigh = ((timestamp & 0xfffffff) * 10000) + 0x1000; // 时间高位加上版本号 1
    const node = '00:11:22:33:44:55'; // 模拟的 MAC 地址
    const random = Math.floor(Math.random() * 0x100000000).toString(16).padStart(8, '0');

    return `${timestamp.toString(16).padStart(8, '0')}-${timeHigh.toString(16)}-${random}-${node.replace(/:/g, '')}`;
}

function generateUUIDv4() {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (char) => {
        const rand = (Math.random() * 16) | 0;
        const value = char === 'x' ? rand : (rand & 0x3) | 0x8;
        return value.toString(16);
    });
}

function generateUUIDv7() {
    const timestamp = BigInt(Date.now()); // 当前时间戳（毫秒）
    const random = crypto.getRandomValues(new Uint8Array(10)); // 随机数生成

    // 时间戳的高位部分（42 位）
    const timestampHigh = timestamp >> 18n;
    // 时间戳的低位部分（12 位）
    const timestampLow = (timestamp & 0x3ffffn).toString(16).padStart(5, '0');

    // 随机数生成（10 字节 = 80 位）
    const randomHex = Array.from(random, byte => byte.toString(16).padStart(2, '0')).join('');

    return `${timestampHigh.toString(16).padStart(8, '0')}-${timestampLow}-${randomHex.slice(0, 4)}-${randomHex.slice(4, 12)}-${randomHex.slice(12)}`;
}

function init() {
    const dataArr = [
        {
            "id": "51793af6-c923-5504-85db-0ef686624dec",
            "name": "39影视",
            "api": "https://www.39kan.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "55ab99ac-60ec-4a3a-835e-803bd60820a5",
            "name": "天堂资源",
            "api": "http://vipmv.cc/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "678047c5-678b-480e-b7e9-2386f93cb1b7",
            "name": "6U资源",
            "api": "http://zy.ataoju.com/inc/api.php",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "4e70d643-476d-4ffa-9a72-a1a9d559ab53",
            "name": "量子资源",
            "api": "http://cj.lziapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "712d6bd7-379b-416c-8882-e4817ac9f30c",
            "name": "FOX资源",
            "api": "https://api.foxzyapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "993d45bb-8fc4-4db9-8ee4-f87e125c08b8",
            "name": "乐活影视",
            "api": "https://lehootv.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "558b9bc3-2acf-4d1c-92f2-63ee8eda3c6f",
            "name": "快播资源",
            "api": "http://www.kuaibozy.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "f33d398e-fe48-4822-8ff4-bf913699d432",
            "name": "百度云资源",
            "api": "https://api.apibdzy.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "786356c9-892f-45e8-8d69-39ca1a0eda9d",
            "name": "tom资源网",
            "api": "https://tomziyuan.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "fbe80b8b-fcfd-4e4e-8c44-31566bb83760",
            "name": "明帝影视",
            "api": "https://ys.md214.cn/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "88b93e11-832d-4bdb-8021-24ea54e1f93c",
            "name": "酷点资源",
            "api": "https://kudianzy.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "3cb534c8-de7d-4e39-ac33-40964c7f41af",
            "name": "淘片资源采集网",
            "api": "https://taopianapi.com/home/cjapi/as/mc10/vod/json",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "16b85c08-7b04-445e-9f26-ccc709e455ba",
            "name": "新浪资源",
            "api": "https://api.xinlangapi.com/xinlangapi.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "91f541f5-3ad1-4110-98f9-2cb63bda68d8",
            "name": "快车资源",
            "api": "https://caiji.kczyapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "807dcda6-e46f-450b-aabb-6e55fe739ce0",
            "name": "鱼乐资源网",
            "api": "https://api.yulecj.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "11d50e5a-4761-49fa-8978-eea0b6077acf",
            "name": "闪电资源网",
            "api": "https://sdzyapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "3ca72cb8-46ff-451f-bbb2-8cadcff26ff9",
            "name": "云解析资源网",
            "api": "https://api.yparse.com/api/json",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "f179322d-b7f5-4ff6-8865-63590d860ed8",
            "name": "CK资源",
            "api": "https://ckzy.me/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "f8174347-ccc0-4476-98e0-d908fcbf580f",
            "name": "光速资源",
            "api": "https://api.guangsuapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "a5e18898-366f-46e2-8444-732caacbce24",
            "name": "金鹰资源",
            "api": "https://jyzyapi.com/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "0b4b9628-0bfa-4580-be27-11231194ffcf",
            "name": "天空资源",
            "api": "https://api.tiankongapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "696a75b0-9fc7-4efa-86cb-db236451274c",
            "name": "飞速资源",
            "api": "https://www.feisuzy.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "000f35de-168c-4b56-8856-04d69208162d",
            "name": "鱼乐资源",
            "api": "https://api.ylzy1.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "c8a6447e-1e19-44c5-82db-5511c0dd181c",
            "name": "飘花资源",
            "api": "http://www.zzrhgg.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "7c1df2ac-2cbd-4f18-8f6e-623e9d9566c5",
            "name": "韩剧资源",
            "api": "http://www.hanjuzy.com/inc/apijson_vod.php",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "adff032d-932a-4b29-98a0-c95c2f192a34",
            "name": "非凡资源",
            "api": "http://cj.ffzyapi.com/api.php/provide/vod/from/ffm3u8/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "91664054-0d97-4931-94d0-adea4bfa6ac0",
            "name": "Ikun资源",
            "api": "https://ikunzyapi.com/api.php/provide/vod",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "2f838d7f-bb47-4529-a70e-20547c4caa78",
            "name": "樱花动漫",
            "api": "https://m3u8.apiyhzy.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "b87596f1-fd4f-4488-8ca9-c58e07edeb3e",
            "name": "rrvipw",
            "api": "https://www.rrvipw.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "2f6ece92-13c2-4590-aeb9-de5df453efc9",
            "name": "1080zyku",
            "api": "http://api.1080zyku.com/inc/api_mac10.php",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "d591d4cc-ba24-4a1e-80f1-806ca3f937f7",
            "name": "U酷资源",
            "api": "https://api.ukuapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "f6bdf248-6966-4ce1-8f0b-d32abb47690c",
            "name": "影图资源",
            "api": "https://cj.vodimg.top/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "ede70aa2-d89b-40c2-ae82-9a1e844312f1",
            "name": "无尽资源",
            "api": "https://api.wujinapi.me/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "c58ddd97-39b6-4d2d-8038-92249b68e75c",
            "name": "南国资源",
            "api": "http://api.nguonphim.tv/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "d504db36-2d89-45e4-8bec-2e1f17c295cd",
            "name": "小猫咪",
            "api": "http://zy.xiaomaomi.cc/api.php/provide/vod/",
            "playUrl": "http://139.159.239.156:88/api/?key=Ydj3I8W80PazAaxvXH&url=",
            "search": 1,
            "group": "官采",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "3325f4d7-1781-4bca-879f-46cea43fe42b",
            "name": "映迷影院",
            "api": "https://www.inmi.app/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "ab717241-442c-4021-880d-89f535c4edf6",
            "name": "1080资源",
            "api": "https://1080p.tv/api.php/provide/vod",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "1d69d2b3-4436-46c5-9872-623fe9c2a0a2",
            "name": "易看资源",
            "api": "https://api.yikanapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "32f8dbc2-9cf1-4820-9f64-0ff5504aaae9",
            "name": "忆梦资源",
            "api": "http://anltv.cn/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "a7c0bf16-d935-4f57-a5b7-4353d0c382b2",
            "name": "TOM资源",
            "api": "https://api.tomcaiji.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "2623fe11-690b-43ed-849d-fc5d64616a11",
            "name": "红牛资源",
            "api": "https://www.hongniuzy2.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "c3f3069b-9e86-4c24-9f30-f84d69f39a63",
            "name": "77韩剧",
            "api": "https://www.77hanju.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "ba1d8759-a498-4bef-8d60-42cc0afe9888",
            "name": "豌豆影院",
            "api": "https://ks.wandouzy.cc/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "综合",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "311ea5ef-7a20-463b-acee-2684d90496fd",
            "name": "干饭",
            "api": "http://124.220.183.81:83/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "官采",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "b3678bc4-9cb0-4ce6-82e6-572b9128837b",
            "name": "肥猫",
            "api": "http://i.xn--z7x900a.love:63/api.php/provide/vod",
            "playUrl": "http://cms.itcxo.cn/v1.vod/icciu_api/chenxi.php?key=微信公众号云烟小助手&url=",
            "search": 1,
            "group": "采集配解析",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "cea6a24a-5650-4e2d-b9ee-e3e7beacbd1f",
            "name": "布蕾",
            "api": "http://117.175.212.198:8088/api.php/app/",
            "playUrl": "",
            "search": 1,
            "group": "app",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "60bda1fc-d64a-469b-bf6f-858e5b439fc0",
            "name": "小龟",
            "api": "https://api123.adys.app/xgapp.php/v3/",
            "playUrl": "",
            "search": 1,
            "group": "app",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "1b7f351f-5ebd-405e-9467-13efa1eaa895",
            "name": "真逗",
            "api": "http://ys.realdou.cn/api.php/app/",
            "playUrl": "",
            "search": 1,
            "group": "app",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "7bb9703f-b9c1-4411-a149-55978f91931f",
            "name": "苹果云视听",
            "api": "https://www.gvideo.me/api.php/app/",
            "playUrl": "",
            "search": 1,
            "group": "app",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "7055cec9-83d6-48a8-858d-42115111ecdd",
            "name": "8848",
            "api": "http://bn.iptv8848.site/api.php/app/",
            "playUrl": "",
            "search": 1,
            "group": "app",
            "isActive": true,
            "type": 1,
            "categories": "电 视,影视"
        },
        {
            "id": "de7e427b-0234-405c-8423-8593fe0d8284",
            "name": "家里有事",
            "api": "http://jlys6.top/mogai_api.php/v1.vod",
            "playUrl": "",
            "search": 1,
            "group": "app",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "40087dff-b2c5-4d46-9b04-ad7997197daf",
            "name": "上次",
            "api": "https://sc1080.top/api.php/v1.vod",
            "playUrl": "",
            "search": 1,
            "group": "app",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "981d126e-cb18-4e80-b808-a74b6b69e3d0",
            "name": "具全",
            "api": "http://xinxing.juquanweb.top/icciu_api.php/v1.vod",
            "playUrl": "",
            "search": 1,
            "group": "app",
            "isActive": true,
            "type": 1,
            "categories": "电视,影 视"
        },
        {
            "id": "ef54155f-97ef-4fc5-803f-42ddc17ec552",
            "name": "瑞丰",
            "api": "http://81.69.23.108:5566/ruifenglb_api.php/v1.vod",
            "playUrl": "",
            "search": 1,
            "group": "app",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "6138eeab-c047-46d5-ba19-de39d70e4060",
            "name": "吃瓜",
            "api": "https://www.chiguafilm.com/api.php/v1.vod",
            "playUrl": "",
            "search": 1,
            "group": "app",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "fbe28d2a-dbe1-4b04-85ac-3bb106a3a9e4",
            "name": "徕米",
            "api": "https://www.laimi.me/api.php/v1.vod?limit=12&page=1",
            "playUrl": "",
            "search": 1,
            "group": "app",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "d771f018-7459-4d67-ba28-5659a985be48",
            "name": "i神520",
            "api": "http://app.ishen520.com/api.php/v1.vod",
            "playUrl": "",
            "search": 1,
            "group": "app",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "31fc9f51-1f3b-47dd-82fd-2bbdc690ef7f",
            "name": "卧龙资源",
            "api": "https://collect.wolongzyw.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "0991905c-5d3e-4fc0-960e-b274ef47b157",
            "name": "量子资源",
            "api": "http://www.lzzy.tv/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "d0150260-019f-4a6c-9ef6-e93580c5fc12",
            "name": "淘片资源采集网",
            "api": "https://taopianapi.com/cjapi/mc10/vod/json.html",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "6a2f6827-76d2-4a18-a397-45a72d35252c",
            "name": "鱼乐资源",
            "api": "https://ylzy11.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "20e25d4b-a0fb-41cc-bbd2-733d872673d4",
            "name": "徕米",
            "api": "https://www.laimi.me/api.php/v1.vod",
            "playUrl": "",
            "search": 1,
            "group": "app",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "a5824572-61d1-4f5d-8863-20ffe0dda0a4",
            "name": "飞速资源",
            "api": "https://www.feisuzyapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "默认",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "e683d481-3ebd-481f-a6e7-7c868ae13e2c",
            "name": "最大资源",
            "api": "https://api.zuidapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "默认",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "29d70941-3be8-48b9-8f3a-8d330baa6cac",
            "name": "奇虎",
            "api": "https://caiji.qhzyapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "影视",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视, 影视"
        },
        {
            "id": "4daf7dbe-ecf3-4e6e-8c82-4bd269288fbd",
            "name": "极速",
            "api": "https://jszyapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "影视",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "fec0d46c-62f7-4096-a266-08f31465d109",
            "name": "海外看[翻墙]",
            "api": "http://api.haiwaikan.com/v1/vod",
            "playUrl": "",
            "search": 1,
            "group": "影视",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "00e62ad4-bc8b-4e28-9019-84933aff15c0",
            "name": "优质资 源网",
            "api": "https://api.1080zyku.com/inc/apijson.php",
            "playUrl": "",
            "search": 1,
            "group": "影视",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "37dd53fe-30bd-4887-a3b7-5741f67887ff",
            "name": "索尼",
            "api": "https://suoniapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "默认",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "d2755737-4388-46f0-8a5a-33ae2c4b3b89",
            "name": "豪华资源",
            "api": "https://hhzyapi.com/api.php/provide/vod",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "6f024f66-d463-4b17-8e6a-2af71337d0bd",
            "name": "虎牙",
            "api": "https://www.huyaapi.com/api.php/provide/vod",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "cac99997-3509-4243-8130-e0c3fba22bca",
            "name": "timizy",
            "api": "https://vipcj.timizy.top/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "官采",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "666a70af-f94d-4ac1-94ab-648b510079f4",
            "name": "KUIN",
            "api": "https://www.kuin.one/api.php/app",
            "playUrl": "",
            "search": 1,
            "group": "app",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "a4365115-7c8a-405a-838d-6db440880173",
            "name": "腐宅",
            "api": "http://app.zhaifutvapp.com/ruifenglb_api.php/v1.vod",
            "playUrl": "",
            "search": 1,
            "group": "app",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "8e635cf2-3c79-4575-8c7f-5b5a9c34acd7",
            "name": "暴风",
            "api": "https://bfzyapi.com/api.php/provide/vod",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "a2d562dc-5d4e-4c97-8fbb-04505e60a0a2",
            "name": "速播",
            "api": "http://suboziyuan.net/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "9824db2c-f802-4f6a-81f4-3f2fa69269da",
            "name": "全站资源",
            "api": "https://caiji.yueai55.cc:2277/yuelove.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "官采",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": " 电视,影视"
        },
        {
            "id": "4d7d91f3-83bf-4613-b4a7-30c49e6ddf4b",
            "name": "爱狗",
            "api": "https://api.i2g.cn/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "官采",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "18621a3c-1d21-4207-9e3f-ddff85725be5",
            "name": "乐视",
            "api": "https://leshizyapi.com/api.php/provide/vod/at/json/",
            "playUrl": "",
            "search": 1,
            "group": "官采",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": "电视,影视"
        },
        {
            "id": "7c856f39-ee41-4b53-8c4b-74ce74a7ee8c",
            "name": "左岸",
            "api": "http://103.97.176.128:9528/api.php/provide/vod/",
            "playUrl": "http://110.42.2.247:8001/analysis/json/?uid=2449&my=acfgikquvzFGJRW459&url=",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "12466dd3-df84-4c12-a5e5-193cb9ec9b83",
            "name": "49资源网",
            "api": " https://49zyw.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "11bac337-e938-471b-8e59-c75e55c89412",
            "name": "快看资源",
            "api": "https://kuaikan-api.com/api.php/provide/vod/from/kuaikanyun",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "7f241dce-db6f-4023-bdce-e62b48ce2e4d",
            "name": "享看资源",
            "api": "https://xkanzy.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "105d8b5d-fb52-43fd-87ba-c731da712afd",
            "name": "魔都动漫",
            "api": "https://caiji.moduapi.cc/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "d7bc47bb-1547-4e9e-a6f7-991e90835ad7",
            "name": "快云资源",
            "api": "https://kuaiyun-api.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "0c315078-772d-4645-a10d-43057b07b3cf",
            "name": "快鹰资源",
            "api": "http://savviuux.hk3.345888.xyz.cdn.cloudflare.net/api.php/provide/vod/",
            "playUrl": "https://stray.serv00.net/ky.php?url=",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "2ef97848-03ba-4c5e-939a-a51079810d6c",
            "name": "AI1",
            "api": "http://124.222.116.5/macos/seven/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "官采",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "411ede3d-34eb-4e1d-873e-49b7251e7e0c",
            "name": "业余自营",
            "api": "http://154.3.2.163/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "categories": "短剧,电影,电视剧,动漫,综艺,记录片,体育"
        },
        {
            "id": "295964bc-78f8-46d0-8d9a-06b0a68c8b7b",
            "name": "非凡资 源",
            "api": "http://www.ffzy.tv/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "默认",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "id": "0bb8bed5-39ce-41c3-bc82-89eaafc56771",
            "name": "ikun资源",
            "api": "https://ikunzyapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "默认",
            "isActive": true,
            "type": 1,
            "categories": "电视,影视"
        },
        {
            "key": "wolongzyw",
            "name": "念心自用 || 卧龙资源",
            "api": "https://collect.wolongzyw.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "status": true,
            "type": 1,
            "id": "3",
            "isActive": true,
            "resource": 65402
        },
        {
            "key": "apibdzy",
            "name": "念心自用 || 百度云资源",
            "api": "https://api.apibdzy.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 0,
            "group": "切片",
            "status": true,
            "type": 1,
            "id": "9",
            "isActive": true,
            "resource": 45356
        },
        {
            "key": "xinlangapi",
            "name": "念心自用 || 新浪资源",
            "api": "https://api.xinlangapi.com/xinlangapi.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "status": true,
            "type": 1,
            "id": "14",
            "isActive": true,
            "resource": 49664
        },
        {
            "key": "快车资源",
            "name": "念心自用 || 快车资源",
            "api": "https://caiji.kczyapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "status": true,
            "type": 1,
            "id": "15",
            "isActive": true,
            "resource": 32575
        },
        {
            "key": "sdzyapi",
            "name": "念心自用 || 闪电资源网",
            "api": "https://sdzyapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "status": true,
            "type": 1,
            "id": "17",
            "isActive": true,
            "resource": 62711
        },
        {
            "key": "guangsuapi",
            "name": "念心自用 || 光速资源",
            "api": "https://api.guangsuapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "status": true,
            "type": 1,
            "id": "20",
            "isActive": true,
            "resource": 49783
        },
        {
            "key": "jyzyapi",
            "name": "念心自用 || 金鹰资源",
            "api": "https://jyzyapi.com/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "status": true,
            "type": 1,
            "id": "21",
            "isActive": true,
            "resource": 49530
        },
        {
            "key": "tiankongapi",
            "name": "念心自用 || 天空资源",
            "api": "https://api.tiankongapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "status": true,
            "type": 1,
            "id": "22",
            "isActive": true,
            "resource": 55389
        },
        {
            "key": "9fbbb48c-d822-55ed-baee-40964804d8a9",
            "name": "念心自用 || Ikun资源",
            "api": "https://ikunzyapi.com/api.php/provide/vod",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "status": true,
            "type": 1,
            "id": "28",
            "isActive": true,
            "resource": 47930
        },
        {
            "key": "apiyhzy",
            "name": "念心自用 || 樱花动漫",
            "api": "https://m3u8.apiyhzy.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "status": false,
            "type": 1,
            "id": "29",
            "isActive": true,
            "resource": 96819
        },
        {
            "key": "1080zyku",
            "name": "念心自用 || 1080zyku",
            "api": "http://api.1080zyku.com/inc/api_mac10.php",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "status": false,
            "type": 1,
            "id": "31",
            "isActive": true,
            "resource": 49381
        },
        {
            "key": "ukuapi",
            "name": "念心自用 || U酷资源",
            "api": "https://api.ukuapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "status": true,
            "type": 1,
            "id": "32",
            "isActive": true,
            "resource": 34968
        },
        {
            "key": "无尽资源",
            "name": "念心自用 || 无尽资源",
            "api": "https://api.wujinapi.me/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "status": true,
            "isActive": true,
            "type": 1,
            "id": "34",
            "resource": 56674
        },
        {
            "key": "映迷影院",
            "name": "念心自用 || 映迷影院",
            "api": "https://www.inmi.app/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "status": true,
            "type": 1,
            "id": "37",
            "isActive": true
        },
        {
            "key": "红牛资源",
            "name": "念心自用 || 红牛资源",
            "api": "https://www.hongniuzy2.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "status": true,
            "type": 1,
            "id": "42",
            "isActive": true,
            "resource": 49335
        },
        {
            "key": "juquanweb",
            "name": "念心自用 || 具全",
            "api": "http://xinxing.juquanweb.top/icciu_api.php/v1.vod",
            "playUrl": "",
            "search": 1,
            "group": "app",
            "status": true,
            "type": 4,
            "id": "54",
            "isActive": true,
            "resource": 131944
        },
        {
            "key": "非凡资源",
            "name": "念心自用 || 非凡资源",
            "api": "http://www.ffzy.tv/api.php/provide/vod/",
            "group": "默认",
            "status": true,
            "isActive": true,
            "type": 1,
            "resource": 62133,
            "id": "59",
            "search": 1,
            "playUrl": ""
        },
        {
            "key": "飞速资源",
            "name": "念心自用 || 飞速资源",
            "api": "https://www.feisuzyapi.com/api.php/provide/vod/",
            "group": "默认",
            "status": true,
            "type": 1,
            "id": "60",
            "search": 1,
            "playUrl": "",
            "isActive": true,
            "resource": 55153
        },
        {
            "key": "最大资源",
            "name": "念心自用 || 最大资源",
            "api": "http://zuidazy.me/api.php/provide/vod/at/xml",
            "group": "默认",
            "status": true,
            "type": 0,
            "search": 1,
            "id": "80",
            "playUrl": "",
            "isActive": true,
            "resource": 37488
        },
        {
            "key": "5ad3edc1-8e52-5bf6-90f1-2f785465ec2a",
            "name": "念心自用 || 奇虎",
            "api": "https://caiji.qhzyapi.com/api.php/provide/vod/?ac=list",
            "playUrl": "奇虎",
            "group": "影视",
            "search": 1,
            "status": true,
            "type": 1,
            "id": "89",
            "isActive": true,
            "resource": 19367
        },
        {
            "key": "a5a4498a-04ae-5267-b11c-a68eb32ff1e8",
            "name": "念心自用 || 极速",
            "api": "https://jszyapi.com/api.php/provide/vod/at/json",
            "playUrl": "https://jsjiexi.com/play/?url=",
            "group": "影视",
            "search": 1,
            "status": true,
            "type": 1,
            "id": "90",
            "isActive": true,
            "resource": 47713
        },
        {
            "key": "bajiecaiji",
            "name": "念心自用 || 八戒采集",
            "api": "https://cj.bajiecaiji.com/inc/apijson.php",
            "group": "影视",
            "status": true,
            "type": 1,
            "search": 1,
            "id": "104",
            "playUrl": "",
            "isActive": true,
            "resource": 1069
        },
        {
            "key": "cb658939-5abf-5d37-81d9-16633d80818e",
            "name": "念心自用 || 优质资源网",
            "api": "https://api.1080zyku.com/inc/apijson.php",
            "download": "",
            "playUrl": "",
            "group": "影视",
            "search": 1,
            "status": true,
            "type": 1,
            "id": "117",
            "isActive": true,
            "resource": 49381
        },
        {
            "key": "cb15e5f4-e058-5766-bb85-f5d2fa28411a",
            "name": "念心自用 || 索尼",
            "api": "https://suoniapi.com/api.php/provide/vod/",
            "download": "",
            "playUrl": "",
            "group": "默认",
            "search": 1,
            "status": true,
            "isActive": true,
            "type": 1,
            "id": "119",
            "resource": 55292
        },
        {
            "key": "51793af6-c923-5504-85db-0ef686624dec",
            "name": "念心自用 || 火狐",
            "api": "https://hhzyapi.com/api.php/provide/vod",
            "download": "",
            "playUrl": "",
            "group": "切片",
            "search": 1,
            "status": true,
            "isActive": true,
            "type": 1,
            "id": "120",
            "resource": 46257
        },
        {
            "key": "4aa0e523-d76f-504b-812a-5fcccfc9d6b8",
            "name": "念心自用 || 虎牙",
            "api": "https://www.huyaapi.com/api.php/provide/vod",
            "download": "",
            "playUrl": "",
            "group": "切片",
            "search": 1,
            "status": true,
            "isActive": true,
            "type": 1,
            "id": "121",
            "resource": 48508
        },
        {
            "key": "014234c3-aa3e-583d-a4f5-87c058843aca",
            "name": "念心自用 || timizy",
            "api": "https://vipcj.timizy.top/api.php/provide/vod/",
            "download": "",
            "playUrl": "",
            "group": "官采",
            "search": 1,
            "status": true,
            "isActive": true,
            "type": 1,
            "id": "122",
            "resource": 33230
        },
        {
            "key": "643043a5-4f08-5313-bc7e-1385967ad6cd",
            "name": "念心自用 || 暴风",
            "api": "https://bfzyapi.com/api.php/provide/vod",
            "download": "",
            "playUrl": "",
            "group": "切片",
            "search": 1,
            "status": true,
            "type": 3,
            "id": "126",
            "isActive": true
        },
        {
            "id": "76489ae3-c843-35a2-860b-58868e8ee4cd",
            "name": "淘片资源",
            "api": "https://taopianapi.com/cjapi/mc10/vod/json.html",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": ""
        },
        {
            "id": "c2ca30e7-897e-f519-3122-7aef7db2fb5c",
            "name": "天空资源",
            "api": "https://api.tiankongapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": ""
        },
        {
            "id": "566fb0e1-8619-09dd-de4a-42ba872737dc",
            "name": "影图资源",
            "api": "https://cj.vodimg.top/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": ""
        },
        {
            "id": "ef2c10e3-8d3f-d632-727b-667fdd2e5b50",
            "name": "无尽资源",
            "api": "https://api.wujinapi.me/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": ""
        },
        {
            "id": "8ed85599-f988-a8d1-41fd-265c4f64a5d9",
            "name": "红牛资源",
            "api": "https://www.hongniuzy2.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": ""
        },
        {
            "id": "136a93b2-9826-af52-d063-dd5b4e637ba5",
            "name": "具全",
            "api": "http://xinxing.juquanweb.top/icciu_api.php/v1.vod",
            "playUrl": "",
            "search": 1,
            "group": "app",
            "isActive": true,
            "type": 4,
            "ext": "",
            "categories": ""
        },
        {
            "id": "f10d2925-a991-1fa1-475f-21ac57ef698f",
            "name": "飞速资源",
            "api": "https://www.feisuzyapi.com/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "默认",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": ""
        },
        {
            "id": "4aa0e523-d76f-504b-812a-5fcccfc9d6b8",
            "name": "虎牙",
            "api": "https://www.huyaapi.com/api.php/provide/vod",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": ""
        },
        {
            "id": "014234c3-aa3e-583d-a4f5-87c058843aca",
            "name": "timizy",
            "api": "https://vipcj.timizy.top/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "官采",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": ""
        },
        {
            "id": "fc028ea5-d479-5253-b247-c11f99d06dda",
            "name": "KUIN",
            "api": "https://www.kuin.one/api.php/app",
            "playUrl": "",
            "search": 1,
            "group": "app",
            "isActive": true,
            "type": 3,
            "ext": "",
            "categories": ""
        },
        {
            "id": "643043a5-4f08-5313-bc7e-1385967ad6cd",
            "name": "暴风",
            "api": "https://bfzyapi.com/api.php/provide/vod",
            "playUrl": "",
            "search": 1,
            "group": "切片",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": ""
        },
        {
            "id": "54e747d7-4a0d-4e71-aaa9-a2272cdb4fc5",
            "name": "全站资源",
            "api": "https://caiji.yueai55.cc:2277/yuelove.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "官采",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": ""
        },
        {
            "id": "8ccd22d8-7405-eda1-668d-950260f50d1e",
            "name": "爱狗",
            "api": "https://api.i2g.cn/api.php/provide/vod/",
            "playUrl": "",
            "search": 1,
            "group": "官采",
            "isActive": true,
            "type": 1,
            "ext": "",
            "categories": ""
        },
        {
            "name": "左岸",
            "api": "http://103.97.176.128:9528/api.php/provide/vod/",
            "playUrl": "http://110.42.2.247:8001/analysis/json/?uid=2449&my=acfgikquvzFGJRW459&url=",
            "group": "切片",
            "search": 1,
            "isActive": true,
            "type": 1,
            "id": "7a0c3c38-d860-465d-9f2d-34bb430f9add"
        },
        {
            "name": "49资源网",
            "api": " https://49zyw.com/api.php/provide/vod/",
            "playUrl": "",
            "group": "切片",
            "search": 1,
            "isActive": true,
            "type": 1,
            "id": "d24a2022-450a-48b6-9051-ac04b398dfdc"
        },
        {
            "name": "享看资源",
            "api": "https://xkanzy.com/api.php/provide/vod/",
            "playUrl": "",
            "group": "切片",
            "search": 1,
            "isActive": true,
            "type": 1,
            "id": "b90da766-fcd4-477e-b595-cd3a23fb85fc"
        },
        {
            "name": "AI1",
            "api": "http://124.222.116.5/macos/seven/api.php/provide/vod/",
            "playUrl": "",
            "group": "官采",
            "search": 1,
            "isActive": true,
            "type": 1,
            "id": "c46de987-070e-4ed7-9844-703f3915128d"
        },
        {
            "key": "快播云",
            "id": 1,
            "name": "快播云",
            "api": "http://www.kuaibozy.com/api.php/provide/vod/from/kbm3u8/at/xml/",
            "download": "",
            "jiexiUrl": "https://jx.7kjx.com/?url=",
            "group": "默认",
            "isActive": true,
            "status": "可用",
            "reverseOrder": true
        },
        {
            "key": "天空云",
            "id": 2,
            "name": "天空云",
            "api": "https://api.tiankongapi.com/api.php/provide/vod/at/xml/from/tkm3u8/",
            "download": "",
            "jiexiUrl": "https://jx.7kjx.com/?url=",
            "group": "默认",
            "isActive": true,
            "reverseOrder": false,
            "status": "可用"
        },
        {
            "key": "八戒云",
            "id": 3,
            "name": "八戒云",
            "api": "http://cj.bajiecaiji.com/inc/bjm3u8.php",
            "download": "",
            "jiexiUrl": "",
            "group": "默认",
            "isActive": true,
            "reverseOrder": false,
            "status": "可用"
        },
        {
            "key": "39影视",
            "id": 5,
            "name": "39影视",
            "api": "https://www.39kan.com/api.php/provide/vod/at/xml",
            "download": "",
            "jiexiUrl": "",
            "group": "默认",
            "isActive": true,
            "reverseOrder": false,
            "status": "可用"
        },
        {
            "key": "8090资源",
            "id": 7,
            "name": "8090资源",
            "api": "http://zy.yilans.net:8090/api.php/provide/vod/at/xml/",
            "download": "",
            "jiexiUrl": "https://9kjx.com/?url=",
            "group": "默认",
            "isActive": true,
            "status": "可用",
            "reverseOrder": false
        },
        {
            "id": 10,
            "key": "ldzyw",
            "name": "乐多资源网",
            "api": "http://api.leduozy.com/inc/api.php",
            "download": "",
            "jiexiUrl": "",
            "group": "常用组",
            "isActive": true,
            "reverseOrder": false,
            "status": "可用"
        },
        {
            "key": "快播资源",
            "id": 14,
            "name": "快播资源",
            "api": "http://www.kuaibozy.com/api.php/provide/vod/at/xml/",
            "download": "",
            "group": "切片",
            "isActive": true,
            "status": "可用",
            "reverseOrder": false
        },
        {
            "key": "八戒资源",
            "id": 16,
            "name": "八戒资源",
            "api": "http://cj.bajiecaiji.com/inc/api.php",
            "download": "",
            "group": "切片",
            "isActive": true,
            "status": "可用",
            "reverseOrder": false
        },
        {
            "key": "天空资源",
            "id": 17,
            "name": "天空资源",
            "api": "http://api.tiankongapi.com/api.php/provide/vod/at/xml/",
            "download": "",
            "group": "切片",
            "isActive": true,
            "status": "可用",
            "reverseOrder": false
        },
        {
            "id": 21,
            "key": "百度资源",
            "name": "百度资源",
            "api": "https://api.apibdzy.com/api.php/provide/vod/at/xml/",
            "download": "",
            "jiexiUrl": "",
            "group": "资源",
            "isActive": true,
            "status": "可用",
            "reverseOrder": false
        },
        {
            "id": 22,
            "key": "美剧星球",
            "name": "美剧星球",
            "api": "https://www.meijuxq.tv/inc/api.php",
            "download": "",
            "jiexiUrl": "",
            "group": "资源",
            "isActive": true,
            "status": "可用",
            "reverseOrder": false
        },
        {
            "id": 24,
            "key": "哇可可影视",
            "name": "哇可可影视",
            "api": "https://www.zwcoco.com/api.php/provide/vod/at/xml/",
            "download": "",
            "jiexiUrl": "",
            "group": "资源",
            "isActive": true,
            "status": "可用",
            "reverseOrder": false
        },
        {
            "id": 25,
            "key": "鱼乐资源",
            "name": "鱼乐资源",
            "api": "https://api.ylzy1.com/api.php/provide/vod/at/xml/",
            "download": "",
            "jiexiUrl": "",
            "group": "资源",
            "isActive": true,
            "status": "可用",
            "reverseOrder": false
        },
        {
            "id": 26,
            "key": "酷点资源",
            "name": "酷点资源",
            "api": "https://api.kuapi.cc/api.php/provide/vod/at/xml/",
            "download": "",
            "jiexiUrl": "",
            "group": "资源",
            "isActive": true,
            "status": "可用",
            "reverseOrder": false
        },
        {
            "id": 27,
            "key": "趣看",
            "name": "趣看",
            "api": "http://qkmp4.cn/api.php/provide/vod/at/xml/",
            "download": "",
            "jiexiUrl": "",
            "group": "资源",
            "isActive": true,
            "status": "可用",
            "reverseOrder": false
        },
        {
            "id": 30,
            "key": "无尽资源",
            "name": "无尽资源",
            "api": "https://wuzy9.com/api.php/provide/vod/at/xml/",
            "download": "",
            "jiexiUrl": "",
            "group": "资源",
            "isActive": true,
            "status": "可用",
            "reverseOrder": false
        },
        {
            "id": 33,
            "key": "樱花资源",
            "name": "樱花资源",
            "api": "https://m3u8.apiyhzy.com/api.php/provide/vod/at/xml/",
            "download": "",
            "jiexiUrl": "",
            "group": "资源",
            "isActive": true,
            "status": "可用",
            "reverseOrder": false
        },
        {
            "id": 34,
            "key": "随便看电影",
            "name": "随便看电影",
            "api": "https://baobei666.com/inc/api.php",
            "download": "",
            "jiexiUrl": "",
            "group": "资源",
            "isActive": true,
            "status": "可用",
            "reverseOrder": false
        },
        {
            "id": 38,
            "key": "闪电资源",
            "name": "闪电资源",
            "api": "http://sdzyapi.com/api.php/provide/vod/at/xml/",
            "download": "",
            "jiexiUrl": "",
            "group": "资源",
            "isActive": true,
            "status": "可用",
            "reverseOrder": false
        },
        {
            "id": 44,
            "key": "千寻时光",
            "name": "千寻时光",
            "api": "http://wy.dqyhg.cn/api.php/provide/vod/at/xml/",
            "download": "",
            "jiexiUrl": "",
            "group": "资源",
            "isActive": true,
            "status": "可用",
            "reverseOrder": false
        }
    ];
    let relArr = [];
    for (let o of dataArr) {
        let isRepeat = false;
        for (let rep of relArr) {
            isRepeat = o.api === rep.api;
            if (isRepeat) break;
        }
        if (!isRepeat) {
            const ki = generateUUIDv4();
            relArr.push({
                "id": ki,
                "key": ki,
                "name": o.name,
                "api": o.api,
                "playUrl": o.playUrl || "",
                "search": o.search || 0,
                "group": o.group || "默认",
                "type": o.type || 1,
                "ext": o.ext || "",
                "categories": o.categories || "电视,影视",
                "isActive": o.isActive || true,
            });
        }
    }
    try {
        // 将对象转换为 JSON 字符串
        const jsonData = JSON.stringify(relArr, null, 2); // 使用 2 个空格缩进，使 JSON 更易读
        fs.writeFileSync('data.json', jsonData);
        console.log('数据已成功写入文件');
    } catch (err) {
        console.error('写入文件时出错:', err);
    }
    console.log(relArr);
}

init();